TARGET = L1_AUDIO
APP_NAME = 
XCC_FLAGS = -Wall -O2 -fsubword-select -DUSB_CORE=0 -g -save-temps
USED_MODULES = module_usb_shared module_xud module_xud_interrupt_driven

#=============================================================================
# The following part of the Makefile includes the common build infrastructure
# for compiling XMOS applications. You should not need to edit below here.


# Use the main Makefile from module_xmos_common
XMOS_MAKE_PATH ?= ../..
include $(XMOS_MAKE_PATH)/xcommon/module_xcommon/build/Makefile.common
